[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/interviewer"
  to = "/index2.html"
  status = 200

[[redirects]]
  from = "/diagnostico"
  to = "/diagnostico.html"
  status = 200

[[redirects]]
  from = "/experience"
  to = "/diagnostico.html"
  status = 301
